variables:
  DOCKER_BUILDKIT: 1
  BUILD_CONFIGURATION: "Release"

  dockerImageName: spydersoft/identity/identity_server
  containerRegistryName: proget_docker
  containerRegistryUrl: proget.mattgerega.com
  dockerImageFileName: identity_server

trigger:
  branches:
    include:
      - master
      - feature/*
  paths:
    exclude:
      - README.md



stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: Default
      demands: agent.os -equals Linux
    steps:
    - template: templates/dotnet-build-steps.yml
    # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your pipeline.
    - publish: '$(Build.ArtifactStagingDirectory)' 
      artifact: 'identityServer'

        
- stage: docker_and_test
  jobs:
  - job: create_docker_image_and_test
    timeoutInMinutes: 90
    pool:
      name: Default
      demands: agent.os -equals Linux
    steps:
    - template: templates/docker-image-steps.yml
      parameters:
        dockerImageName: $(dockerImageName)
        containerRegistryName: $(containerRegistryName)
        containerRegistryUrl: $(containerRegistryUrl)
        artifactName: 'identityServer'
        dockerImageFileName: $(dockerImageFileName)
