sonar.projectKey=spyder007_identity_admin_ui
sonar.projectName=identity_admin_ui
sonar.organization=spydersoft-mjg

sonar.projectBaseDir=source/Spydersoft.Identity.Admin.Frontend/admin-ui

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/output/**,**/src/api/**

sonar.javascript.lcov.reportPaths=output/coverage/lcov.info
sonar.typescript.lcov.reportPaths=output/coverage/lcov.info

sonar.sourceEncoding=UTF-8
