## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: BitBucket
      endpoint: "Bitbucket - spydersoft"
      name: spydersoftteam/azure-devops-templates
    - repository: helmfileconfig
      type: BitBucket
      endpoint: Bitbucket - spydersoft
      name: spydersoftteam/id-helm-config-repo

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr: none

extends:
  template: stages/stages-build-docker-update-helm/v1.yml@templates
  parameters:
    buildProject: source/spydersoft.Identity.sln
    publishProject: source/spydersoft.Identity/spydersoft.Identity.csproj
    artifactName: identityServer
    artifactZipName: spydersoft.Identity
    dockerImageFileName: identity_server
    dockerImageName: spydersoft/identity/identity_server
    imageTagVariableName: identity_server
    helmfileRepoName: helmfileconfig
    sonar_endpoint_name: sonarqube
    sonar_project_key: identity_identity_AYV-QkChmblgg6j_jAeV
    sonar_project_name: identity_server
    execute_sonar: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
    execute_tests: true
    prebuildSteps:
      - task: Npm@1
        displayName: NPM Install
        inputs:
          workingDir: $(Build.SourcesDirectory)/source/spydersoft.Identity
          command: install
      - task: CmdLine@2
        inputs:
          script: 'npm install gulp' 
          workingDirectory: $(Build.SourcesDirectory)/source/spydersoft.Identity
      - task: CmdLine@2
        inputs:
          script: 'gulp build:dist'
          workingDirectory: $(Build.SourcesDirectory)/source/spydersoft.Identity
    preTestSteps:
      - pwsh:
          Copy-Item $(Build.SourcesDirectory)/source/spydersoft.identity.tests/bin/Release/net6.0/refs/Microsoft.AspNetCore.Http.Features.dll $(Build.SourcesDirectory)/source/spydersoft.identity.tests/bin/Release/net6.0
