## Build Pipeline - Build, publish container image, and update helmfile config
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates
    - repository: helmfileconfig
      type: github
      endpoint: spyder007
      name: spyder007/id-helm-config

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md

pr: none


extends:
  template: pipelines/build-api/v1.yml@templates
  parameters:
    buildProject: source/Spydersoft.Identity.sln
    publishProject: src/Spydersoft.TechRadar.Data.Api.csproj
    netCoreVersion: '8.0.x'
    artifactName: identityServer
    artifactZipName: Spydersoft.Identity
    dockerImageName: spydersoft/identity/identity_server
    dockerFilePath: Dockerfile.simple
    imageTagVariableName: identity_server
    helmfileRepoName: helmfileconfig
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      updateHelmConfig: false
      buildAndPublishDockerImage: false
    ${{ else }}:
      updateHelmConfig: true
      buildAndPublishDockerImage: true
    sonar_endpoint_name: sonarcloud-spydersoft
    sonar_project_key: spyder007_identity_server
    sonar_project_name: identity_server
    execute_sonar: true
    execute_tests: true
    test_projects: '**/*.Tests/*.csproj'
    use_sonarcloud: true
    sonar_cloud_organization: spydersoft-mjg
    prebuildSteps:
      - task: Npm@1
        displayName: NPM Install
        inputs:
          workingDir: $(Build.SourcesDirectory)/source/Spydersoft.Identity
          command: install
      - task: CmdLine@2
        inputs:
          script: 'npm install gulp' 
          workingDirectory: $(Build.SourcesDirectory)/source/Spydersoft.Identity
      - task: CmdLine@2
        inputs:
          script: 'gulp build:dist'
          workingDirectory: $(Build.SourcesDirectory)/source/Spydersoft.Identity
